# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 14:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ztc.utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BesluitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('besluittype_omschrijving', models.CharField(blank=True, help_text='Omschrijving van de aard van BESLUITen van het BESLUITTYPE.', max_length=80, null=True, verbose_name='besluittype omschrijving')),
                ('besluittype_omschrijving_generiek', models.CharField(blank=True, help_text='Algemeen gehanteerde omschrijving van de aard van BESLUITen van het BESLUITTYPE', max_length=80, null=True, verbose_name='besluittype omschrijving generiek')),
                ('besluitcategorie', models.CharField(blank=True, help_text='Typering van de aard van BESLUITen van het BESLUITTYPE.', max_length=40, null=True, verbose_name='besluitcategorie')),
                ('reactietermijn', models.PositiveSmallIntegerField(help_text='Het aantal dagen, gerekend vanaf de verzend- of publicatiedatum, waarbinnen verweer tegen een besluit van het besluittype mogelijk is.', validators=[django.core.validators.MaxValueValidator(999)], verbose_name='reactietermijn')),
                ('publicatie_indicatie', models.CharField(choices=[('J', 'Ja'), ('N', 'Nee')], help_text='Aanduiding of BESLUITen van dit BESLUITTYPE gepubliceerd moeten worden.', max_length=1, verbose_name='publicatie indicatie')),
                ('publicatietekst', models.TextField(blank=True, help_text='De generieke tekst van de publicatie van BESLUITen van dit BESLUITTYPE', max_length=1000, null=True, verbose_name='publicatietekst')),
                ('publicatietermijn', models.PositiveSmallIntegerField(blank=True, help_text='Het aantal dagen, gerekend vanaf de verzend- of publicatiedatum, dat BESLUITen van dit BESLUITTYPE gepubliceerd moeten blijven.', null=True, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='publicatietermijn')),
                ('toelichting', models.TextField(blank=True, help_text='Een eventuele toelichting op dit BESLUITTYPE.', max_length=1000, null=True, verbose_name='toelichting')),
                ('datum_begin_geldigheid_besluittype', ztc.utils.fields.StUFDateField(help_text='De datum waarop het BESLUITTYPE is ontstaan.', max_length=9, verbose_name='datum begin geldigheid besluittype')),
                ('datum_einde_geldigheid_besluittype', ztc.utils.fields.StUFDateField(blank=True, help_text='De datum waarop het BESLUITTYPE is opgeheven.', max_length=9, null=True, verbose_name='datum einde geldigheid besluittype')),
            ],
        ),
        migrations.CreateModel(
            name='Catalogus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domein', models.CharField(help_text='Een afkorting waarmee wordt aangegeven voor welk domein in een CATALOGUS', max_length=5, validators=[django.core.validators.RegexValidator('^[A-Z]*$')], verbose_name='domein')),
                ('rsin', models.CharField(help_text='Het door een kamer toegekend uniek nummer voor de INGESCHREVEN NIET-NATUURLIJK PERSOON die de eigenaar is van een CATALOGUS.', max_length=9, verbose_name='rsin')),
                ('contactpersoon_beheer_naam', models.CharField(help_text='De naam van de contactpersoon die verantwoordelijk is voor het beheer van de CATALOGUS.', max_length=40, verbose_name='contactpersoon beheer naam')),
                ('contactpersoon_beheer_telefoonnummer', models.CharField(blank=True, help_text='Het telefoonnummer van de contactpersoon die verantwoordelijk is voor het beheer van de CATALOGUS.', max_length=20, null=True, verbose_name='contactpersoon beheer telefoonnummer')),
                ('contactpersoon_beheer_emailadres', models.EmailField(blank=True, help_text='Het emailadres van de contactpersoon die verantwoordelijk is voor het beheer van de CATALOGUS.', max_length=254, null=True, verbose_name='contactpersoon beheer emailadres')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='catalogus',
            unique_together=set([('domein', 'rsin')]),
        ),
        migrations.AddField(
            model_name='besluittype',
            name='maakt_deel_uit_van',
            field=models.ForeignKey(help_text='De CATALOGUS waartoe dit BESLUITTYPE behoort.', on_delete=django.db.models.deletion.CASCADE, to='datamodel.Catalogus', verbose_name='maakt deel uit van Catalogus'),
        ),
        migrations.AlterUniqueTogether(
            name='besluittype',
            unique_together=set([('maakt_deel_uit_van', 'besluittype_omschrijving')]),
        ),
    ]
