# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 16:51
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ztc.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eigenschap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eigenschapnaam', models.CharField(help_text='De naam van de EIGENSCHAP', max_length=20, verbose_name='eigenschapnaam')),
                ('definitie', models.CharField(help_text='De beschrijving van de betekenis van deze EIGENSCHAP', max_length=255, verbose_name='definitie')),
                ('toelichting', models.TextField(blank=True, help_text='Een toelichting op deze EIGENSCHAP en het belang hiervan voor zaken van dit ZAAKTYPE.', max_length=1000, null=True, verbose_name='toelichting')),
                ('datum_begin_geldigheid_eigenschap', ztc.utils.fields.StUFDateField(help_text='De datum waarop de EIGENSCHAP is ontstaan.', max_length=9, verbose_name='datum begin geldigheid eigenschap')),
                ('datum_einde_geldigheid_eigenschap', ztc.utils.fields.StUFDateField(blank=True, help_text='De datum waarop de EIGENSCHAP is opgeheven.', max_length=9, null=True, verbose_name='datum einde geldigheid eigenschap')),
            ],
        ),
        migrations.CreateModel(
            name='EigenschapReferentie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objecttype', models.CharField(blank=True, help_text='De naam van het objecttype waarbij de eigenschap is gemodelleerd in het informatiemodel waarvan het objecttype deel uit maakt.', max_length=40, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9 _]*$')], verbose_name='objecttype')),
                ('informatiemodel', models.CharField(blank=True, help_text='De naam en de versie van het informatiemodel waarin de eigenschap is gemodelleerd.', max_length=80, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_]*$')], verbose_name='informatiemodel')),
                ('namespace', models.CharField(help_text='De naam van het schema waarin de eigenschap is opgenomen.', max_length=200, verbose_name='namespace')),
                ('schemalocatie', models.CharField(help_text='De locatie van het XML-schema behorend bij de Namespace', max_length=200, verbose_name='schemalocatie')),
                ('x_path_element', models.CharField(blank=True, help_text='De naam van de eigenschap en het pad daarnaar toe in het XML-schema behorend bij de namespace.', max_length=255, null=True, verbose_name='x path element')),
                ('entiteittype', models.CharField(help_text='De naam van de XML-constructie in het XML-schema behorend bij de namespace die afgeleid is van de naam van het objecttype en waarin de eigenschap is opgenomen.', max_length=80, verbose_name='entiteittype')),
            ],
        ),
        migrations.CreateModel(
            name='EigenschapSpecificatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groep', models.CharField(blank=True, help_text='Benaming van het object of groepattribuut waarvan de EIGENSCHAP een inhoudelijk gegeven specificeert.', max_length=32, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_]*$')], verbose_name='groep')),
                ('formaat', models.CharField(help_text='Het soort tekens waarmee waarden van de EIGENSCHAP kunnen worden vastgelegd.', max_length=20, verbose_name='formaat')),
                ('lengte', models.CharField(help_text='Het aantal karakters (lengte) waarmee waarden van de EIGENSCHAP worden vastgelegd.', max_length=14, verbose_name='lengte')),
                ('kardinaliteit', models.CharField(help_text='Het aantal mogelijke voorkomens van waarden van deze EIGENSCHAP bij een zaak van het ZAAKTYPE.', max_length=3, verbose_name='kardinaliteit')),
                ('waardenverzameling', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='Een waarde die deze EIGENSCHAP kan hebben.', max_length=100, verbose_name='waardenverzameling'), size=None)),
            ],
        ),
        migrations.AddField(
            model_name='eigenschap',
            name='referentie_naar_eigenschap',
            field=models.ForeignKey(blank=True, help_text='Verwijzing naar de standaard waarin de eigenschap is gespecificeerd', null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.EigenschapReferentie', verbose_name='referentie naar eigenschap'),
        ),
        migrations.AddField(
            model_name='eigenschap',
            name='specificatie_van_eigenschap',
            field=models.ForeignKey(blank=True, help_text='Attribuutkenmerken van de eigenschap', null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.EigenschapSpecificatie', verbose_name='specificatie van eigenschap'),
        ),
    ]
