# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 15:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ztc.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultaatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_begin_geldigheid', ztc.utils.fields.StUFDateField(help_text='De datum waarop het is ontstaan.', max_length=9, verbose_name='datum begin geldigheid')),
                ('datum_einde_geldigheid', ztc.utils.fields.StUFDateField(blank=True, help_text='De datum waarop het is opgeheven.', max_length=9, null=True, verbose_name='datum einde geldigheid')),
                ('resultaattypeomschrijving', models.CharField(help_text='Omschrijving van de aard van resultaten van het RESULTAATTYPE.', max_length=20, verbose_name='resultaattypeomschrijving')),
                ('resultaattypeomschrijving_generiek', models.CharField(help_text='Algemeen gehanteerde omschrijving van de aard van resultaten van het RESULTAATTYPE.', max_length=20, verbose_name='resultaattypeomschrijving generiek')),
                ('selectielijstklasse', models.CharField(blank=True, help_text='Verwijzing naar de, voor het archiefregime bij het RESULTAATTYPE relevante, passage in de Selectielijst Archiefbescheiden van de voor het ZAAKTYPE verantwoordelijke overheidsorganisatie.', max_length=500, null=True, verbose_name='selectielijstklasse')),
                ('archiefnominatie', models.CharField(choices=[('blijvend_bewaren', 'blijvend bewaren'), ('vernietigen', 'vernietigen')], help_text='Aanduiding die aangeeft of ZAAKen met een resultaat van dit RESULTAATTYPE blijvend moeten worden bewaard of (op termijn) moeten worden vernietigd .', max_length=16, verbose_name='archiefnominatie')),
                ('archiefactietermijn', models.PositiveSmallIntegerField(help_text='De termijn waarna het zaakdossier (de ZAAK met alle bijbehorende INFORMATIEOBJECTen) van een ZAAK met een resultaat van dit RESULTAATTYPE vernietigd of overgebracht (naar een archiefbewaarplaats) moet worden.', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='archiefactietermijn')),
                ('brondatum_archiefprocedure', models.CharField(choices=[('afgehandeld', 'afgehandeld'), ('ingangsdatum_besluit', 'ingangsdatum besluit'), ('vervaldatum_besluit', 'vervaldatum besluit'), ('eigenschap', 'eigenschap'), ('ander_datumkenmerk', 'ander datumkenmerk')], help_text='Aanduiding van de brondatum voor de start van de Archiefactietermijn van het zaakdossier.', max_length=20, verbose_name='brondatum archiefprocedure')),
                ('toelichting', models.CharField(blank=True, help_text='Een toelichting op dit RESULTAATTYPE en het belang hiervan voor ZAAKen waarin een Resultaat van dit RESULTAATTYPE wordt geselecteerd.', max_length=1000, null=True, verbose_name='toelichting')),
                ('heeft_voor_brondatum_archiefprocedure_relevante', models.ForeignKey(blank=True, help_text='De EIGENSCHAP die bepalend is voor het moment waarop de Archiefactietermijn start voor een ZAAK met een resultaat van dit RESULTAATTYPE.', null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.Eigenschap', verbose_name='heeft voor brondatum archiefprocedure relevante')),
            ],
        ),
    ]
