# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0002_resultaattype'),
    ]

    operations = [
        migrations.AddField(
            model_name='besluittype',
            name='is_resultaat_van',
            field=models.ManyToManyField(help_text='(inverse van:) Het BESLUITTYPE van besluiten die gepaard gaan met resultaten van het RESULTAATTYPE.', related_name='leidt_tot', to='datamodel.ResultaatType', verbose_name='is resultaat van'),
        ),
    ]
