# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 10:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0002_auto_20180130_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='besluittype',
            options={'ordering': ('maakt_deel_uit_van', 'besluittype_omschrijving'), 'verbose_name': 'Besluittype', 'verbose_name_plural': 'Besluittypen'},
        ),
        migrations.AlterModelOptions(
            name='catalogus',
            options={'ordering': ('domein', 'rsin'), 'verbose_name': 'Catalogus', 'verbose_name_plural': 'Catalogussen'},
        ),
        migrations.AlterModelOptions(
            name='eigenschap',
            options={'ordering': ('is_van', 'eigenschapnaam'), 'verbose_name': 'Eigenschap', 'verbose_name_plural': 'Eigenschappen'},
        ),
        migrations.AlterModelOptions(
            name='informatieobjecttype',
            options={'ordering': ('maakt_deel_uit_van', 'informatieobjecttype_omschrijving'), 'verbose_name': 'Informatieobjecttype', 'verbose_name_plural': 'Informatieobjecttypen'},
        ),
        migrations.AlterModelOptions(
            name='resultaattype',
            options={'ordering': ('is_relevant_voor', 'resultaattypeomschrijving'), 'verbose_name': 'Resultaattype', 'verbose_name_plural': 'Resultaattypen'},
        ),
        migrations.AlterModelOptions(
            name='roltype',
            options={'ordering': ('is_van', 'roltypeomschrijving'), 'verbose_name': 'Roltype', 'verbose_name_plural': 'Roltypen'},
        ),
        migrations.AlterModelOptions(
            name='statustype',
            options={'ordering': ('is_van', 'statustypevolgnummer'), 'verbose_name': 'Statustype', 'verbose_name_plural': 'Statustypen'},
        ),
        migrations.AlterModelOptions(
            name='zaakinformatieobjecttype',
            options={'ordering': ('zaaktype', 'volgnummer'), 'verbose_name': 'Zaak-Informatieobject-Type', 'verbose_name_plural': 'Zaak-Informatieobject-Typen'},
        ),
        migrations.AlterModelOptions(
            name='zaakinformatieobjecttypearchiefregime',
            options={'ordering': ('pk',), 'verbose_name': 'Zaak-Informatieobject-Type Archiefregime', 'verbose_name_plural': 'Zaak-Informatieobject-Type Archiefregimes'},
        ),
        migrations.AlterModelOptions(
            name='zaakobjecttype',
            options={'ordering': ('is_relevant_voor', 'objecttype'), 'verbose_name': 'Zaakobjecttype', 'verbose_name_plural': 'Zaakobjecttypen'},
        ),
        migrations.AlterModelOptions(
            name='zaaktype',
            options={'ordering': ('maakt_deel_uit_van', 'zaaktype_identificatie'), 'verbose_name': 'Zaaktype', 'verbose_name_plural': 'Zaaktypen'},
        ),
        migrations.AlterModelOptions(
            name='zaaktypenrelatie',
            options={'ordering': ('pk',), 'verbose_name': 'Zaaktypenrelatie', 'verbose_name_plural': 'Zaaktypenrelaties'},
        ),
        migrations.AlterField(
            model_name='eigenschap',
            name='toelichting',
            field=models.CharField(blank=True, help_text='Een toelichting op deze EIGENSCHAP en het belang hiervan voor zaken van dit ZAAKTYPE.', max_length=1000, null=True, verbose_name='toelichting'),
        ),
        migrations.AlterField(
            model_name='informatieobjecttype',
            name='toelichting',
            field=models.CharField(blank=True, help_text='Een eventuele toelichting op dit INFORMATIEOBJECTTYPE.', max_length=1000, null=True, verbose_name='toelichting'),
        ),
        migrations.AlterField(
            model_name='zaakinformatieobjecttype',
            name='volgnummer',
            field=models.PositiveSmallIntegerField(help_text='Uniek volgnummer van het ZAAK-INFORMATIEOBJECT-TYPE binnen het ZAAKTYPE.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='volgnummer'),
        ),
        migrations.AlterUniqueTogether(
            name='zaakinformatieobjecttype',
            unique_together=set([('zaaktype', 'volgnummer')]),
        ),
        migrations.AlterUniqueTogether(
            name='zaakinformatieobjecttypearchiefregime',
            unique_together=set([('zaak_informatieobject_type', 'resultaattype')]),
        ),
        migrations.AlterUniqueTogether(
            name='zaaktypenrelatie',
            unique_together=set([('zaaktype_van', 'zaaktype_naar')]),
        ),
    ]
