# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 11:57
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import ztc.datamodel.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0002_auto_20171128_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformatieObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informatieobjecttype_omschrijving', models.CharField(help_text='Omschrijving van de aard van informatieobjecten van dit INFORMATIEOBJECTTYPE.', max_length=80, verbose_name='informatieobjecttype omschrijving')),
                ('informatieobjectcategorie', models.CharField(help_text='Typering van de aard van informatieobjecten van dit INFORMATIEOBJECTTYPE.', max_length=80, verbose_name='informatieobjectcategorie')),
                ('informatieobjecttypetrefwoord', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='Trefwoord(en) waarmee informatieobjecten van het INFORMATIEOBJECTTYPE kunnen worden gekarakteriseerd.', max_length=30, verbose_name='informatieobjecttypetrefwoord'), size=None)),
                ('vertrouwelijkheidaanduiding', models.CharField(blank=True, choices=[('zeer_geheim', 'zeer geheim'), ('geheim', 'geheim'), ('confidentieel', 'confidentieel'), ('vertrouwelijk', 'vertrouwelijk'), ('zaakvertrouwelijk', 'zaakvertrouwelijk'), ('intern', 'intern'), ('beperkt_openbaar', 'beperkt openbaar'), ('openbaar', 'openbaar')], help_text='Aanduiding van de mate waarin informatieobjecten van dit INFORMATIEOBJECTTYPE voor de openbaarheid bestemd zijn.', max_length=20, null=True, verbose_name='vertrouwelijkheidaanduiding')),
                ('model', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(help_text='De URL naar het model / sjabloon dat wordt gebruikt voor de creatie van informatieobjecten van dit INFORMATIEOBJECTTYPE.', verbose_name='model'), size=None)),
                ('toelichting', models.TextField(blank=True, help_text='Een eventuele toelichting op dit INFORMATIEOBJECTTYPE.', max_length=1000, null=True, verbose_name='toelichting')),
            ],
            bases=(ztc.datamodel.models.mixins.GeldigheidMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InformatieObjectTypeOmschrijvingGeneriek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informatieobjecttype_omschrijving_generiek', models.CharField(help_text='Algemeen gehanteerde omschrijving van het type informatieobject.', max_length=80, verbose_name='informatieobjecttype omschrijving generiek')),
                ('definitie_informatieobjecttype_omschrijving_generiek', models.CharField(help_text='Nauwkeurige beschrijving van het generieke type informatieobject', max_length=255, verbose_name='definitie informatieobjecttype omschrijving generiek')),
                ('herkomst_informatieobjecttype_omschrijving_generiek', models.CharField(help_text='De naam van de waardenverzameling, of van de beherende organisatie daarvan, waaruit de waarde is overgenomen.', max_length=12, verbose_name='herkomst informatieobjecttype omschrijving generiek')),
                ('hierarchie_informatieobjecttype_omschrijving_generiek', models.CharField(help_text='De plaats in de rangorde van het informatieobjecttype.', max_length=80, verbose_name='hierarchie informatieobjecttype omschrijving generiek')),
                ('opmerking_informatieobjecttype_omschrijving_generiek', models.CharField(blank=True, help_text='Zinvolle toelichting bij het informatieobjecttype', max_length=255, null=True, verbose_name='opmerking informatieobjecttype omschrijving generiek')),
            ],
            bases=(ztc.datamodel.models.mixins.GeldigheidMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='eigenschapspecificatie',
            name='formaat',
            field=models.CharField(choices=[('tekst', 'tekst'), ('getal', 'getal'), ('datum', 'datum (jjjjmmdd)'), ('datum_tijd', 'datum (jjjjmmdduummss)')], help_text='Het soort tekens waarmee waarden van de EIGENSCHAP kunnen worden vastgelegd.', max_length=20, verbose_name='formaat'),
        ),
        migrations.AddField(
            model_name='informatieobjecttype',
            name='informatieobjecttype_omschrijving_generiek',
            field=models.ForeignKey(blank=True, help_text='Algemeen gehanteerde omschrijving van het INFORMATIEOBJECTTYPE.', null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.InformatieObjectTypeOmschrijvingGeneriek', verbose_name='informatieobjecttype omschrijving generiek'),
        ),
    ]
