# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 16:27
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import ztc.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0003_besluittype_is_resultaat_van'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_begin_geldigheid', ztc.utils.fields.StUFDateField(help_text='De datum waarop het is ontstaan.', max_length=9, verbose_name='datum begin geldigheid')),
                ('datum_einde_geldigheid', ztc.utils.fields.StUFDateField(blank=True, help_text='De datum waarop het is opgeheven.', max_length=9, null=True, verbose_name='datum einde geldigheid')),
                ('roltypeomschrijving', models.CharField(help_text='Omschrijving van de aard van de ROL.', max_length=20, verbose_name='roltypeomschrijving')),
                ('roltypeomschrijving_generiek', models.CharField(choices=[('adviseur', 'adviseur'), ('behandelaar', 'behandelaar'), ('belanghebbende', 'belanghebbende'), ('beslisser', 'beslisser'), ('initiator', 'initiator'), ('klantcontacter', 'klantcontacter'), ('zaakcoordinator', 'zaakcoördinator')], help_text='Algemeen gehanteerde omschrijving van de aard van de ROL.', max_length=20, verbose_name='roltypeomschrijving generiek')),
                ('soort_betrokkene', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='De (soort) betrokkene die een rol van dit roltype mag uitoefenen.', max_length=80, verbose_name='soort betrokkene'), size=None)),
            ],
        ),
    ]
