# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-26 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0003_auto_20180221_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broncatalogus',
            options={'verbose_name': 'Bron catalogus', 'verbose_name_plural': 'Bron catalogussen'},
        ),
        migrations.AlterModelOptions(
            name='bronzaaktype',
            options={'verbose_name': 'Bron zaaktype', 'verbose_name_plural': 'Bron zaaktypen'},
        ),
        migrations.AlterModelOptions(
            name='formulier',
            options={'verbose_name': 'Formulier', 'verbose_name_plural': 'Formulieren'},
        ),
        migrations.AlterModelOptions(
            name='productdienst',
            options={'verbose_name': 'Product / Dienst', 'verbose_name_plural': 'Product / Diensten'},
        ),
        migrations.AlterModelOptions(
            name='referentieproces',
            options={'verbose_name': 'Referentieprocess', 'verbose_name_plural': 'Referentieprocessen'},
        ),
    ]
