# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0003_auto_20171129_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='besluittype',
            name='datum_begin_geldigheid_besluittype',
        ),
        migrations.RemoveField(
            model_name='besluittype',
            name='datum_einde_geldigheid_besluittype',
        ),
        migrations.RemoveField(
            model_name='eigenschap',
            name='datum_begin_geldigheid_eigenschap',
        ),
        migrations.RemoveField(
            model_name='eigenschap',
            name='datum_einde_geldigheid_eigenschap',
        ),
    ]
