# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 13:06
from __future__ import unicode_literals

from django.db import migrations
import ztc.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0004_auto_20171129_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='besluittype',
            name='datum_begin_geldigheid',
            field=ztc.utils.fields.StUFDateField(default=None, help_text='De datum waarop het is ontstaan.', max_length=9, verbose_name='datum begin geldigheid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='besluittype',
            name='datum_einde_geldigheid',
            field=ztc.utils.fields.StUFDateField(blank=True, help_text='De datum waarop het is opgeheven.', max_length=9, null=True, verbose_name='datum einde geldigheid'),
        ),
        migrations.AddField(
            model_name='eigenschap',
            name='datum_begin_geldigheid',
            field=ztc.utils.fields.StUFDateField(default=None, help_text='De datum waarop het is ontstaan.', max_length=9, verbose_name='datum begin geldigheid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eigenschap',
            name='datum_einde_geldigheid',
            field=ztc.utils.fields.StUFDateField(blank=True, help_text='De datum waarop het is opgeheven.', max_length=9, null=True, verbose_name='datum einde geldigheid'),
        ),
        migrations.AddField(
            model_name='informatieobjecttype',
            name='datum_begin_geldigheid',
            field=ztc.utils.fields.StUFDateField(default=None, help_text='De datum waarop het is ontstaan.', max_length=9, verbose_name='datum begin geldigheid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informatieobjecttype',
            name='datum_einde_geldigheid',
            field=ztc.utils.fields.StUFDateField(blank=True, help_text='De datum waarop het is opgeheven.', max_length=9, null=True, verbose_name='datum einde geldigheid'),
        ),
        migrations.AddField(
            model_name='informatieobjecttypeomschrijvinggeneriek',
            name='datum_begin_geldigheid',
            field=ztc.utils.fields.StUFDateField(default=None, help_text='De datum waarop het is ontstaan.', max_length=9, verbose_name='datum begin geldigheid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informatieobjecttypeomschrijvinggeneriek',
            name='datum_einde_geldigheid',
            field=ztc.utils.fields.StUFDateField(blank=True, help_text='De datum waarop het is opgeheven.', max_length=9, null=True, verbose_name='datum einde geldigheid'),
        ),
    ]
