# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 10:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import ztc.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0004_roltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemnaam', models.CharField(help_text='De betekenisvolle benaming van het checklistitem', max_length=30, verbose_name='itemnaam')),
                ('vraagstelling', models.CharField(help_text='Een betekenisvolle vraag waaruit blijkt waarop het aandachtspunt gecontroleerd moet worden.', max_length=255, verbose_name='vraagstelling')),
                ('verplicht', models.CharField(choices=[('J', 'Ja'), ('N', 'Nee')], help_text='Het al dan niet verplicht zijn van controle van het aandachtspunt voorafgaand aan het bereiken van de status van het gerelateerde STATUSTYPE.', max_length=1, verbose_name='verplicht')),
                ('toelichting', models.CharField(blank=True, help_text='Beschrijving van de overwegingen bij het controleren van het aandachtspunt', max_length=1000, null=True, verbose_name='toelichting')),
            ],
        ),
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_begin_geldigheid', ztc.utils.fields.StUFDateField(help_text='De datum waarop het is ontstaan.', max_length=9, verbose_name='datum begin geldigheid')),
                ('datum_einde_geldigheid', ztc.utils.fields.StUFDateField(blank=True, help_text='De datum waarop het is opgeheven.', max_length=9, null=True, verbose_name='datum einde geldigheid')),
                ('statustype_omschrijving', models.CharField(help_text='Een korte, voor de initiator van de zaak relevante, omschrijving van de aard van de STATUS van zaken van een ZAAKTYPE.', max_length=80, verbose_name='statustype omschrijving')),
                ('statustype_omschrijving_generiek', models.CharField(blank=True, help_text='Algemeen gehanteerde omschrijving van de aard van STATUSsen van het STATUSTYPE', max_length=80, null=True, verbose_name='statustype omschrijving generiek')),
                ('statustypevolgnummer', models.PositiveSmallIntegerField(help_text='Een volgnummer voor statussen van het STATUSTYPE binnen een zaak.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='statustypevolgnummer')),
                ('doorlooptijd_status', models.PositiveSmallIntegerField(blank=True, help_text='De door de zaakbehandelende organisatie(s) gestelde norm voor de doorlooptijd voor het bereiken van statussen van dit STATUSTYPE bij het desbetreffende ZAAKTYPE, vanaf het bereiken van de voorafgaande status', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='doorlooptijd status')),
                ('informeren', models.CharField(choices=[('J', 'Ja'), ('N', 'Nee')], help_text='Aanduiding die aangeeft of na het zetten van een STATUS van dit STATUSTYPE de Initiator moet worden geïnformeerd over de statusovergang.', max_length=1, verbose_name='informeren')),
                ('statustekst', models.CharField(blank=True, help_text='De tekst die wordt gebruikt om de Initiator te informeren over het bereiken van een STATUS van dit STATUSTYPE bij het desbetreffende ZAAKTYPE.', max_length=1000, null=True, verbose_name='statustekst')),
                ('toelichting', models.CharField(blank=True, help_text='Een eventuele toelichting op dit STATUSTYPE.', max_length=1000, null=True, verbose_name='toelichting')),
                ('checklistitem', models.ManyToManyField(blank=True, help_text='Te controleren aandachtspunt voorafgaand aan het bereiken van een status van het STATUSTYPE.', to='datamodel.CheckListItem', verbose_name='checklistitem')),
            ],
        ),
    ]
