# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import ztc.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0005_checklistitem_statustype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZaakObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_begin_geldigheid', ztc.utils.fields.StUFDateField(help_text='De datum waarop het is ontstaan.', max_length=9, verbose_name='datum begin geldigheid')),
                ('datum_einde_geldigheid', ztc.utils.fields.StUFDateField(blank=True, help_text='De datum waarop het is opgeheven.', max_length=9, null=True, verbose_name='datum einde geldigheid')),
                ('objecttype', models.CharField(help_text='De naam van het objecttype waarop zaken van het gerelateerde ZAAKTYPE betrekking hebben.', max_length=50, verbose_name='objecttype')),
                ('ander_objecttype', models.CharField(choices=[('J', 'Ja'), ('N', 'Nee')], help_text='Aanduiding waarmee wordt aangegeven of het ZAAKOBJECTTYPE een ander, niet in RSGB en RGBZ voorkomend, objecttype betreft', max_length=1, verbose_name='ander objecttype')),
                ('relatieomschrijving', models.CharField(help_text='Omschrijving van de betrekking van het Objecttype op zaken van het gerelateerde ZAAKTYPE.', max_length=80, verbose_name='relatieomschrijving')),
            ],
        ),
    ]
