# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0006_besluittype_wordt_vastgelegd_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='informatieobjecttype',
            name='maakt_deel_uit_van',
            field=models.ForeignKey(default=None, help_text='De CATALOGUS waartoe dit INFORMATIEOBJECTTYPE behoort.', on_delete=django.db.models.deletion.CASCADE, to='datamodel.Catalogus', verbose_name='maakt deel uit van'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='besluittype',
            name='wordt_vastgelegd_in',
            field=models.ManyToManyField(blank=True, help_text='Het INFORMATIEOBJECTTYPE van informatieobjecten waarin besluiten van dit BESLUITTYPE worden vastgelegd.', to='datamodel.InformatieObjectType'),
        ),
    ]
