# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0007_auto_20171129_1427'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='informatieobjecttype',
            unique_together=set([('maakt_deel_uit_van', 'informatieobjecttype_omschrijving')]),
        ),
    ]
