# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 15:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import ztc.datamodel.validators


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0008_auto_20171129_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besluittype',
            name='publicatietekst',
            field=models.CharField(blank=True, help_text='De generieke tekst van de publicatie van BESLUITen van dit BESLUITTYPE', max_length=1000, null=True, verbose_name='publicatietekst'),
        ),
        migrations.AlterField(
            model_name='besluittype',
            name='toelichting',
            field=models.CharField(blank=True, help_text='Een eventuele toelichting op dit BESLUITTYPE.', max_length=1000, null=True, verbose_name='toelichting'),
        ),
        migrations.AlterField(
            model_name='catalogus',
            name='domein',
            field=models.CharField(help_text='Een afkorting waarmee wordt aangegeven voor welk domein in een CATALOGUS ZAAKTYPEn zijn uitgewerkt.', max_length=5, validators=[django.core.validators.RegexValidator('^[A-Z]*$')], verbose_name='domein'),
        ),
        migrations.AlterField(
            model_name='eigenschapspecificatie',
            name='kardinaliteit',
            field=models.CharField(help_text='Het aantal mogelijke voorkomens van waarden van deze EIGENSCHAP bij een zaak van het ZAAKTYPE.', max_length=3, validators=[ztc.datamodel.validators.KardinaliteitValidator], verbose_name='kardinaliteit'),
        ),
    ]
