# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-18 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0011_auto_20180618_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statustype',
            name='statustekst',
            field=models.CharField(blank=True, default='', help_text='De tekst die wordt gebruikt om de Initiator te informeren over het bereiken van een STATUS van dit STATUSTYPE bij het desbetreffende ZAAKTYPE.', max_length=1000, verbose_name='statustekst'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statustype',
            name='statustype_omschrijving_generiek',
            field=models.CharField(blank=True, default='', help_text='Algemeen gehanteerde omschrijving van de aard van STATUSsen van het STATUSTYPE', max_length=80, verbose_name='omschrijving generiek'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zaaktype',
            name='zaaktype_omschrijving_generiek',
            field=models.CharField(blank=True, default='', help_text='Algemeen gehanteerde omschrijving van de aard van ZAAKen van het ZAAKTYPE', max_length=80, verbose_name='omschrijving generiek'),
            preserve_default=False,
        ),
    ]
