# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-24 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0013_auto_20180709_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogus',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', null=True),
        ),
        migrations.AddField(
            model_name='eigenschap',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', null=True),
        ),
        migrations.AddField(
            model_name='statustype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', null=True),
        ),
        migrations.AddField(
            model_name='zaaktype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', null=True),
        ),
    ]
