# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-09 15:45
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0018_auto_20180730_1637")]

    operations = [
        migrations.AlterModelOptions(
            name="roltype",
            options={"verbose_name": "Roltype", "verbose_name_plural": "Roltypen"},
        ),
        migrations.RenameField(
            model_name="roltype",
            old_name="roltypeomschrijving",
            new_name="omschrijving",
        ),
        migrations.RenameField(
            model_name="roltype",
            old_name="roltypeomschrijving_generiek",
            new_name="omschrijving_generiek",
        ),
        migrations.RenameField(
            model_name="roltype", old_name="is_van", new_name="zaaktype"
        ),
        migrations.AlterField(
            model_name="roltype",
            name="soort_betrokkene",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    max_length=80, verbose_name="soort betrokkene"
                ),
                default=list,
                help_text="De (soort) betrokkene die een rol van dit roltype mag uitoefenen. (Gebruik een komma om waarden van elkaar te onderscheiden.)",
                size=None,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roltype", unique_together=set([("zaaktype", "omschrijving_generiek")])
        ),
    ]
