# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-09 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0019_auto_20180809_1745")]

    operations = [
        migrations.AlterField(
            model_name="roltype",
            name="omschrijving_generiek",
            field=models.CharField(
                choices=[
                    ("Adviseur", "Adviseur"),
                    ("Behandelaar", "Behandelaar"),
                    ("Belanghebbende", "Belanghebbende"),
                    ("Beslisser", "Beslisser"),
                    ("Initiator", "Initiator"),
                    ("Klantcontacter", "Klantcontacter"),
                    ("Zaakcoördinator", "Zaakcoördinator"),
                ],
                help_text="Algemeen gehanteerde omschrijving van de aard van de ROL.",
                max_length=20,
                verbose_name="omschrijving generiek",
            ),
        )
    ]
