# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-13 10:11
from __future__ import unicode_literals

import uuid

from django.db import migrations


def set_uuids(apps, _):
    RolType = apps.get_model('datamodel', 'RolType')
    MogelijkeBetrokkene = apps.get_model('datamodel', 'MogelijkeBetrokkene')
    for model in (RolType, MogelijkeBetrokkene):
        for obj in model.objects.all():
            obj.uuid = uuid.uuid4()
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0022_auto_20180813_1211'),
    ]

    operations = [
        migrations.RunPython(set_uuids, migrations.RunPython.noop),
    ]
