# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-13 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0023_auto_20180813_1211")]

    operations = [
        migrations.AlterField(
            model_name="mogelijkebetrokkene",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name="roltype",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
