# Generated by Django 2.0.8 on 2018-09-06 16:00

from django.db import migrations, models
import vng_api_common.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0027_auto_20180906_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='besluittype', name='publicatietermijn'
        ),
        migrations.RemoveField(
            model_name='besluittype', name='reactietermijn'
        ),

        migrations.AlterField(
            model_name='besluittype',
            name='besluitcategorie',
            field=models.CharField(blank=True, default='', help_text='Typering van de aard van BESLUITen van het BESLUITTYPE.', max_length=40, verbose_name='besluitcategorie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='besluittype',
            name='omschrijving',
            field=models.CharField(blank=True, default='', help_text='Omschrijving van de aard van BESLUITen van het BESLUITTYPE.', max_length=80, verbose_name='omschrijving'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='besluittype',
            name='omschrijving_generiek',
            field=models.CharField(blank=True, default='', help_text='Algemeen gehanteerde omschrijving van de aard van BESLUITen van het BESLUITTYPE', max_length=80, verbose_name='omschrijving generiek'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='besluittype',
            name='publicatie_indicatie',
            field=models.BooleanField(help_text='Aanduiding of BESLUITen van dit BESLUITTYPE gepubliceerd moeten worden.', verbose_name='publicatie indicatie'),
        ),
        migrations.AlterField(
            model_name='besluittype',
            name='publicatietekst',
            field=models.TextField(blank=True, default='', help_text='De generieke tekst van de publicatie van BESLUITen van dit BESLUITTYPE', max_length=1000, verbose_name='publicatietekst'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='besluittype',
            name='publicatietermijn',
            field=vng_api_common.fields.DaysDurationField(blank=True, help_text='Het aantal dagen, gerekend vanaf de verzend- of publicatiedatum, dat BESLUITen van dit BESLUITTYPE gepubliceerd moeten blijven.', max_duration=999, min_duration=1, null=True, verbose_name='publicatietermijn'),
        ),
        migrations.AddField(
            model_name='besluittype',
            name='reactietermijn',
            field=vng_api_common.fields.DaysDurationField(blank=True, help_text='Het aantal dagen, gerekend vanaf de verzend- of publicatiedatum, waarbinnen verweer tegen een besluit van het besluittype mogelijk is.', max_duration=999, min_duration=1, null=True, verbose_name='reactietermijn'),
        ),
        migrations.AlterField(
            model_name='besluittype',
            name='resultaattypes',
            field=models.ManyToManyField(help_text='(inverse van:) Het BESLUITTYPE van besluiten die gepaard gaan met resultaten van het RESULTAATTYPE.', to='datamodel.ResultaatType', verbose_name='is resultaat van'),
        ),
        migrations.AlterField(
            model_name='besluittype',
            name='toelichting',
            field=models.CharField(blank=True, default='', help_text='Een eventuele toelichting op dit BESLUITTYPE.', max_length=1000, verbose_name='toelichting'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='besluittype',
            name='zaaktypes',
            field=models.ManyToManyField(help_text='ZAAKTYPE met ZAAKen die relevant kunnen zijn voor dit BESLUITTYPE', to='datamodel.ZaakType', verbose_name='zaaktypes'),
        ),
    ]
