# Generated by Django 2.0.8 on 2018-09-11 08:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0028_auto_20180906_1800")]

    operations = [
        migrations.AddField(
            model_name="besluittype",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unieke resource identifier (UUID4)",
                null=True,
            ),
        )
    ]
