# Generated by Django 2.0.8 on 2018-09-11 08:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0030_set_besluittype_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besluittype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', unique=True),
        ),
    ]
