# Generated by Django 2.0.8 on 2018-12-11 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0033_auto_20181203_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statustype',
            options={'ordering': ('zaaktype', 'statustypevolgnummer'), 'verbose_name': 'Statustype', 'verbose_name_plural': 'Statustypen'},
        ),
        migrations.RenameField(
            model_name='statustype',
            old_name='is_van',
            new_name='zaaktype',
        ),
        migrations.AlterUniqueTogether(
            name='statustype',
            unique_together={('zaaktype', 'statustypevolgnummer')},
        ),
    ]
