# Generated by Django 2.0.9 on 2019-01-14 11:46

from django.db import migrations


# to postgres types
MAPPING = {
    'J': 'TRUE',
    'N': 'FALSE',
}

REVERSE_MAPPING = {value: key for key, value in MAPPING.items()}


def operation_factory(field: str, mapping: dict):

    def operation(apps, _):
        ZaakType = apps.get_model('datamodel.ZaakType')

        for old, new in mapping.items():
            filter_kwargs = {field: old}
            update_kwargs = {field: new}
            ZaakType.objects.filter(**filter_kwargs).update(**update_kwargs)

    return operation


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0045_auto_20190114_1246'),
    ]

    operations = [
        migrations.RunPython(
            operation_factory('opschorting_aanhouding_mogelijk', MAPPING),
            operation_factory('opschorting_aanhouding_mogelijk', REVERSE_MAPPING)
        ),
        migrations.RunPython(
            operation_factory('verlenging_mogelijk', MAPPING),
            operation_factory('verlenging_mogelijk', REVERSE_MAPPING)
        ),
        migrations.RunPython(
            operation_factory('publicatie_indicatie', MAPPING),
            operation_factory('publicatie_indicatie', REVERSE_MAPPING)
        ),
    ]
