# Generated by Django 2.0.9 on 2019-01-14 14:46

from django.db import migrations

import zds_schema.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0048_auto_20190114_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zaaktype',
            old_name='verlengingstermijn',
            new_name='old_verlengingstermijn',
        ),
        migrations.AddField(
            model_name='zaaktype',
            name='verlengingstermijn',
            field=zds_schema.fields.DaysDurationField(blank=True, help_text="De termijn in dagen waarmee de Doorlooptijd behandeling van ZAAKen van dit ZAAKTYPE kan worden verlengd. Specifieer de duur als 'DD 00:00'", max_duration=999, min_duration=1, null=True, verbose_name='verlengingstermijn'),
        ),
    ]
