# Generated by Django 2.0.9 on 2019-01-14 14:47
from datetime import timedelta

from django.db import migrations


def ints_to_timedelta(apps, _):
    ZaakType = apps.get_model("datamodel.ZaakType")

    ZaakType.objects.filter(verlenging_mogelijk=False).update(verlengingstermijn=None)

    for zaak in ZaakType.objects.filter(verlenging_mogelijk=True):
        zaak.verlengingstermijn = timedelta(days=zaak.old_verlengingstermijn)
        zaak.save()


def timedelta_to_ints(apps, _):
    ZaakType = apps.get_model("datamodel.ZaakType")

    # not nullable, but we don't know what it should be...
    ZaakType.objects.filter(verlenging_mogelijk=False).update(old_verlengingstermijn=1)

    for zaak in ZaakType.objects.filter(verlenging_mogelijk=True):
        zaak.old_verlengingstermijn = zaak.verlengingstermijn.days
        zaak.save()


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0049_auto_20190114_1546")]

    operations = [migrations.RunPython(ints_to_timedelta, timedelta_to_ints)]
