# Generated by Django 2.0.9 on 2019-01-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0050_convert_verlengingstermijn")]

    operations = [
        migrations.RemoveField(model_name="zaaktype", name="old_verlengingstermijn")
    ]
