# Generated by Django 2.0.9 on 2019-01-14 15:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0051_remove_zaaktype_old_verlengingstermijn")]

    operations = [
        migrations.AlterField(
            model_name="zaaktype",
            name="trefwoord",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=30, verbose_name="trefwoord"),
                blank=True,
                help_text="Een trefwoord waarmee ZAAKen van het ZAAKTYPE kunnen worden gekarakteriseerd (gebruik een komma om waarden van elkaar te onderscheiden).",
                size=None,
            ),
        )
    ]
