# Generated by Django 2.0.9 on 2019-01-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0054_auto_20190114_1616")]

    operations = [
        migrations.AlterField(
            model_name="zaaktype",
            name="publicatietekst",
            field=models.TextField(
                blank=True,
                default="",
                help_text="De generieke tekst van de publicatie van ZAAKen van dit ZAAKTYPE.",
                verbose_name="publicatietekst",
            ),
            preserve_default=False,
        )
    ]
