# Generated by Django 2.0.9 on 2019-01-15 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0056_auto_20190114_1654")]

    operations = [
        migrations.RenameField(
            model_name="zaaktype",
            old_name="referentieproces",
            new_name="referentieproces_old",
        )
    ]
