# Generated by Django 2.0.9 on 2019-01-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0057_auto_20190115_1028")]

    operations = [
        migrations.AddField(
            model_name="zaaktype",
            name="referentieproces_link",
            field=models.URLField(
                blank=True,
                help_text="De URL naar de beschrijving van het Referentieproces",
                verbose_name="referentieproceslink",
            ),
        ),
        migrations.AddField(
            model_name="zaaktype",
            name="referentieproces_naam",
            field=models.CharField(
                default="",
                help_text="De naam van het Referentieproces.",
                max_length=80,
                verbose_name="referentieprocesnaam",
            ),
            preserve_default=False,
        ),
    ]
