# Generated by Django 2.0.9 on 2019-01-15 09:32

from django.db import migrations


def migrate_referentieproces_data(apps, _):
    ZaakType = apps.get_model('datamodel.ZaakType')

    for zaaktype in ZaakType.objects.all():
        zaaktype.referentieproces_naam = zaaktype.referentieproces_old.naam
        zaaktype.referentieproces_link = zaaktype.referentieproces_old.link or ''
        zaaktype.save()


def migrate_referentieproces_data_reverse(apps, _):
    ZaakType = apps.get_model('datamodel.ZaakType')
    ReferentieProces = apps.get_model('datamodel.ReferentieProces')

    for zaaktype in ZaakType.objects.all():
        referentieproces, _ = ReferentieProces.objects.get_or_create(
            naam=zaaktype.referentieproces_naam,
            link=zaaktype.referentieproces_link
        )
        zaaktype.referentieproces_old = referentieproces
        zaaktype.save()


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0058_auto_20190115_1032'),
    ]

    operations = [
        migrations.RunPython(
            migrate_referentieproces_data,
            migrate_referentieproces_data_reverse
        )
    ]
