# Generated by Django 2.0.9 on 2019-01-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0060_remove_zaaktype_referentieproces_old")]

    operations = [migrations.DeleteModel(name="ReferentieProces")]
