# Generated by Django 2.0.9 on 2019-01-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0064_auto_20190115_1301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDienst',
        ),
    ]
