# Generated by Django 2.0.9 on 2019-01-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0065_delete_productdienst")]

    operations = [
        migrations.AddField(
            model_name="zaaktype",
            name="selectielijst_procestype",
            field=models.URLField(
                blank=True,
                help_text="Een vanuit archiveringsoptiek onderkende groep processen met dezelfde kenmerken. URL naar de referentielijsten API.",
                verbose_name="selectielijst procestype",
            ),
        )
    ]
