# Generated by Django 2.0.9 on 2019-01-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0069_migrate_zaaktyperelaties")]

    operations = [
        migrations.RemoveField(model_name="zaaktypenrelatie", name="zaaktype_naar")
    ]
