# Generated by Django 2.0.9 on 2019-01-17 09:37
import uuid

from django.db import migrations


def set_uuid(apps, _):
    ZaakInformatieobjectType = apps.get_model('datamodel.ZaakInformatieobjectType')
    for ziot in ZaakInformatieobjectType.objects.all():
        ziot.uuid = uuid.uuid4()
        ziot.save()


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0071_auto_20190117_1037'),
    ]

    operations = [
        migrations.RunPython(set_uuid, migrations.RunPython.noop),
    ]
