# Generated by Django 2.0.9 on 2019-01-17 09:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0072_set_uuid_ziot")]

    operations = [
        migrations.AlterField(
            model_name="zaakinformatieobjecttype",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unieke resource identifier (UUID4)",
                unique=True,
            ),
        )
    ]
