# Generated by Django 2.0.9 on 2019-02-20 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0077_auto_20190220_1147")]

    operations = [
        migrations.AlterModelOptions(
            name="resultaattype",
            options={
                "verbose_name": "resultaattype",
                "verbose_name_plural": "resultaattypen",
            },
        )
    ]
