# Generated by Django 2.0.10 on 2019-02-25 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0086_auto_20190225_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultaattype',
            old_name='_archiefnominatie',
            new_name='archiefnominatie',
        ),
    ]
