# Generated by Django 2.0.10 on 2019-02-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0087_auto_20190225_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultaattype',
            name='brondatum_archiefprocedure_procestermijn',
            field=models.DurationField(blank=True, help_text="De periode dat het zaakdossier na afronding van de zaak actief gebruikt en/of geraadpleegd wordt ter ondersteuning van de taakuitoefening van de organisatie. Enkel relevant indien de afleidingswijze 'termijn' is.", null=True, verbose_name='procestermijn'),
        ),
    ]
