# Generated by Django 2.0.10 on 2019-02-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0088_resultaattype_brondatum_archiefprocedure_procestermijn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultaattype',
            name='brondatum_archiefprocedure_objecttype',
            field=models.CharField(blank=True, choices=[('VerblijfsObject', 'Verblijfsobject'), ('MeldingOpenbareRuimte', 'Melding openbare ruimte'), ('InzageVerzoek', 'Inzage verzoek in het kader van de AVG')], help_text='Het soort object in de registratie dat het procesobject representeert.', max_length=80, verbose_name='objecttype'),
        ),
    ]
