# Generated by Django 2.0.10 on 2019-02-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0090_auto_20190226_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultaattype',
            old_name='_archiefactietermijn',
            new_name='archiefactietermijn',
        ),
    ]
