# Generated by Django 2.0.10 on 2019-03-04 15:20

import relativedeltafield
from django.db import migrations
from dateutil.relativedelta import relativedelta


def convert_days_to_years(period_field):
    # base = 365 days
    res = period_field
    if period_field:
        quotient, remainder = divmod(period_field.days, 365)
        if remainder == 0 and quotient > 0:
            res = relativedelta(years=quotient)
    return res


def update_interval(apps, schema_editor):
    Resultaattype = apps.get_model('datamodel', 'resultaattype')
    for resultaattype in Resultaattype.objects.all():
        resultaattype.archiefactietermijn = convert_days_to_years(resultaattype.archiefactietermijn)
        resultaattype.brondatum_archiefprocedure_procestermijn = convert_days_to_years(
            resultaattype.brondatum_archiefprocedure_procestermijn
        )
        resultaattype.save()


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0092_auto_20190226_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultaattype',
            name='archiefactietermijn',
            field=relativedeltafield.RelativeDeltaField(blank=True, help_text='De termijn, na het vervallen van het bedrjfsvoeringsbelang, waarna het zaakdossier (de ZAAK met alle bijbehorende INFORMATIEOBJECTen) van een ZAAK met een resultaat van dit RESULTAATTYPE vernietigd of overgebracht (naar een archiefbewaarplaats) moet worden. Voor te vernietigen dossiers betreft het de in die Selectielijst genoemde bewaartermjn. Voor blijvend te bewaren zaakdossiers betreft het de termijn vanaf afronding van de zaak tot overbrenging (de procestermijn is dan nihil).', null=True, verbose_name='archiefactietermijn'),
        ),
        migrations.AlterField(
            model_name='resultaattype',
            name='brondatum_archiefprocedure_procestermijn',
            field=relativedeltafield.RelativeDeltaField(blank=True, help_text="De periode dat het zaakdossier na afronding van de zaak actief gebruikt en/of geraadpleegd wordt ter ondersteuning van de taakuitoefening van de organisatie. Enkel relevant indien de afleidingswijze 'termijn' is.", null=True, verbose_name='procestermijn'),
        ),

        migrations.RunPython(update_interval),
    ]
