# Generated by Django 2.0.13 on 2019-03-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0093_auto_20190305_1555")]

    operations = [
        migrations.AlterModelOptions(
            name="informatieobjecttype",
            options={
                "verbose_name": "Informatieobjecttype",
                "verbose_name_plural": "Informatieobjecttypen",
            },
        )
    ]
