# Generated by Django 2.0.13 on 2019-03-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0094_auto_20190305_1557"),
        ("datamodel", "0093_auto_20190304_1620"),
    ]

    operations = []
