# Generated by Django 2.0.13 on 2019-06-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0095_merge_20190327_1650")]

    operations = [
        migrations.AlterUniqueTogether(name="zaaktype", unique_together=set())
    ]
