# Generated by Django 2.0.13 on 2019-06-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0099_auto_20190620_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='besluittype',
            name='draft',
            field=models.BooleanField(default=True, help_text='Flag indicating the object is a draft', verbose_name='draft'),
        ),
        migrations.AddField(
            model_name='informatieobjecttype',
            name='draft',
            field=models.BooleanField(default=True, help_text='Flag indicating the object is a draft', verbose_name='draft'),
        ),
        migrations.AddField(
            model_name='zaaktype',
            name='draft',
            field=models.BooleanField(default=True, help_text='Flag indicating the object is a draft', verbose_name='draft'),
        ),
    ]
