# Generated by Django 2.0.9 on 2019-01-15 15:52

from django.db import migrations


def update_concept(apps, schema_editor):
    ZaakType = apps.get_model('datamodel.ZaakType')
    BesluitType = apps.get_model('datamodel.BesluitType')
    InformatieObjectType = apps.get_model('datamodel.InformatieObjectType')

    for model in [ZaakType, BesluitType, InformatieObjectType]:
        for model_object in model.objects.all():
            model_object.concept = False
            model_object.save()


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0100_auto_20190621_1021'),
    ]

    operations = [
        migrations.RunPython(update_concept),
    ]
