# Generated by Django 2.0.13 on 2019-07-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0101_update_concept")]

    operations = [
        migrations.AlterField(
            model_name="resultaattype",
            name="brondatum_archiefprocedure_objecttype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("adres", "Adres"),
                    ("besluit", "Besluit"),
                    ("buurt", "Buurt"),
                    ("enkelvoudigDocument", "Enkelvoudig document"),
                    ("gemeente", "Gemeente"),
                    ("gemeentelijkeOpenbareRuimte", "Gemeentelijke openbare ruimte"),
                    ("huishouden", "Huishouden"),
                    ("inrichtingselement", "Inrichtingselement"),
                    ("kadastraleOnroerendeZaak", "Kadastrale onroerende zaak"),
                    ("kunstwerkdeel", "Kunstwerkdeel"),
                    ("maatschappelijkeActiviteit", "Maatschappelijke activiteit"),
                    ("medewerker", "Medewerker"),
                    ("natuurlijkPersoon", "Natuurlijk persoon"),
                    ("nietNatuurlijkPersoon", "Niet-natuurlijk persoon"),
                    ("openbareRuimte", "Openbare ruimte"),
                    ("organisatorischeEenheid", "Organisatorische eenheid"),
                    ("pand", "Pand"),
                    ("spoorbaandeel", "Spoorbaandeel"),
                    ("status", "Status"),
                    ("terreindeel", "Terreindeel"),
                    ("terreinGebouwdObject", "Terrein gebouwd object"),
                    ("vestiging", "Vestiging"),
                    ("waterdeel", "Waterdeel"),
                    ("wegdeel", "Wegdeel"),
                    ("wijk", "Wijk"),
                    ("woonplaats", "Woonplaats"),
                    ("wozDeelobject", "Woz deel object"),
                    ("wozObject", "Woz object"),
                    ("wozWaarde", "Woz waarde"),
                    ("zakelijkRecht", "Zakelijk recht"),
                    ("overige", "Overige"),
                ],
                help_text="Het soort object in de registratie dat het procesobject representeert.",
                max_length=80,
                verbose_name="objecttype",
            ),
        )
    ]
