# Generated by Django 2.2.3 on 2019-07-12 16:33

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields
import vng_api_common.fields


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0102_auto_20190703_1045")]

    operations = [
        migrations.AlterField(
            model_name="eigenschapspecificatie",
            name="formaat",
            field=models.CharField(
                choices=[
                    ("tekst", "Tekst"),
                    ("getal", "Getal"),
                    ("datum (jjjjmmdd)", "Datum"),
                    ("datum/tijd (jjjjmmdduummss)", "Datum/tijd"),
                ],
                help_text="Het soort tekens waarmee waarden van de EIGENSCHAP kunnen worden vastgelegd.",
                max_length=20,
                verbose_name="formaat",
            ),
        ),
        migrations.AlterField(
            model_name="informatieobjecttype",
            name="vertrouwelijkheidaanduiding",
            field=vng_api_common.fields.VertrouwelijkheidsAanduidingField(
                choices=[
                    ("openbaar", "Openbaar"),
                    ("beperkt_openbaar", "Beperkt openbaar"),
                    ("intern", "Intern"),
                    ("zaakvertrouwelijk", "Zaakvertrouwelijk"),
                    ("vertrouwelijk", "Vertrouwelijk"),
                    ("confidentieel", "Confidentieel"),
                    ("geheim", "Geheim"),
                    ("zeer_geheim", "Zeer geheim"),
                ],
                help_text="Aanduiding van de mate waarin informatieobjecten van dit INFORMATIEOBJECTTYPE voor de openbaarheid bestemd zijn.",
                max_length=20,
                verbose_name="vertrouwelijkheidaanduiding",
            ),
        ),
        migrations.AlterField(
            model_name="mogelijkebetrokkene",
            name="betrokkene_type",
            field=models.CharField(
                choices=[
                    ("natuurlijk_persoon", "Natuurlijk persoon"),
                    ("niet_natuurlijk_persoon", "Niet-natuurlijk persoon"),
                    ("vestiging", "Vestiging"),
                    ("organisatorische_eenheid", "Organisatorische eenheid"),
                    ("medewerker", "Medewerker"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="resultaattype",
            name="brondatum_archiefprocedure_objecttype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("adres", "Adres"),
                    ("besluit", "Besluit"),
                    ("buurt", "Buurt"),
                    ("enkelvoudig_document", "Enkelvoudig document"),
                    ("gemeente", "Gemeente"),
                    ("gemeentelijke_openbare_ruimte", "Gemeentelijke openbare ruimte"),
                    ("huishouden", "Huishouden"),
                    ("inrichtingselement", "Inrichtingselement"),
                    ("kadastrale_onroerende_zaak", "Kadastrale onroerende zaak"),
                    ("kunstwerkdeel", "Kunstwerkdeel"),
                    ("maatschappelijke_activiteit", "Maatschappelijke activiteit"),
                    ("medewerker", "Medewerker"),
                    ("natuurlijk_persoon", "Natuurlijk persoon"),
                    ("niet_natuurlijk_persoon", "Niet-natuurlijk persoon"),
                    ("openbare_ruimte", "Openbare ruimte"),
                    ("organisatorische_eenheid", "Organisatorische eenheid"),
                    ("pand", "Pand"),
                    ("spoorbaandeel", "Spoorbaandeel"),
                    ("status", "Status"),
                    ("terreindeel", "Terreindeel"),
                    ("terrein_gebouwd_object", "Terrein gebouwd object"),
                    ("vestiging", "Vestiging"),
                    ("waterdeel", "Waterdeel"),
                    ("wegdeel", "Wegdeel"),
                    ("wijk", "Wijk"),
                    ("woonplaats", "Woonplaats"),
                    ("woz_deelobject", "Woz deel object"),
                    ("woz_object", "Woz object"),
                    ("woz_waarde", "Woz waarde"),
                    ("zakelijk_recht", "Zakelijk recht"),
                    ("overige", "Overige"),
                ],
                help_text="Het soort object in de registratie dat het procesobject representeert.",
                max_length=80,
                verbose_name="objecttype",
            ),
        ),
        migrations.AlterField(
            model_name="roltype",
            name="omschrijving_generiek",
            field=models.CharField(
                choices=[
                    ("adviseur", "Adviseur"),
                    ("behandelaar", "Behandelaar"),
                    ("belanghebbende", "Belanghebbende"),
                    ("beslisser", "Beslisser"),
                    ("initiator", "Initiator"),
                    ("klantcontacter", "Klantcontacter"),
                    ("zaakcoordinator", "Zaakcoördinator"),
                    ("mede_initiator", "Mede-initiator"),
                ],
                help_text="Algemeen gehanteerde omschrijving van de aard van de ROL.",
                max_length=20,
                verbose_name="omschrijving generiek",
            ),
        ),
        migrations.AlterField(
            model_name="zaakinformatieobjecttype",
            name="richting",
            field=models.CharField(
                choices=[
                    ("inkomend", "Inkomend"),
                    ("intern", "Intern"),
                    ("uitgaand", "Uitgaand"),
                ],
                help_text="Aanduiding van de richting van informatieobjecten van het gerelateerde INFORMATIEOBJECTTYPE bij zaken van het gerelateerde ZAAKTYPE.",
                max_length=20,
                verbose_name="richting",
            ),
        ),
        migrations.AlterField(
            model_name="zaakinformatieobjecttypearchiefregime",
            name="archiefnominatie",
            field=models.CharField(
                choices=[
                    ("blijvend_bewaren", "Blijvend bewaren"),
                    ("vernietigen", "Vernietigen"),
                ],
                help_text="Aanduiding die aangeeft of informatieobjecten, van het INFORMATIEOBJECTTYPE bij zaken van het ZAAKTYPE met een resultaat van het RESULTAATTYPE, blijvend moeten worden bewaard of (op termijn) moeten worden vernietigd.",
                max_length=16,
                verbose_name="archiefnominatie",
            ),
        ),
        migrations.AlterField(
            model_name="zaaktype",
            name="indicatie_intern_of_extern",
            field=models.CharField(
                choices=[("intern", "Intern"), ("extern", "Extern")],
                help_text="Een aanduiding waarmee onderscheid wordt gemaakt tussen ZAAKTYPEn die Intern respectievelijk Extern geïnitieerd worden. Indien van beide sprake kan zijn, dan prevaleert de externe initiatie.",
                max_length=6,
                verbose_name="indicatie intern of extern",
            ),
        ),
        migrations.AlterField(
            model_name="zaaktype",
            name="producten_of_diensten",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.URLField(
                    max_length=1000, verbose_name="URL naar product/dienst"
                ),
                help_text="Het product of de dienst die door ZAAKen van dit ZAAKTYPE wordt voortgebracht.",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="zaaktype",
            name="trefwoorden",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=30, verbose_name="trefwoord"),
                blank=True,
                default=list,
                help_text="Een trefwoord waarmee ZAAKen van het ZAAKTYPE kunnen worden gekarakteriseerd.",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="zaaktype",
            name="verantwoordingsrelatie",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(
                    max_length=40, verbose_name="verantwoordingsrelatie"
                ),
                blank=True,
                default=list,
                help_text="De relatie tussen ZAAKen van dit ZAAKTYPE en de beleidsmatige en/of financiële verantwoording.",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="zaaktype",
            name="vertrouwelijkheidaanduiding",
            field=vng_api_common.fields.VertrouwelijkheidsAanduidingField(
                choices=[
                    ("openbaar", "Openbaar"),
                    ("beperkt_openbaar", "Beperkt openbaar"),
                    ("intern", "Intern"),
                    ("zaakvertrouwelijk", "Zaakvertrouwelijk"),
                    ("vertrouwelijk", "Vertrouwelijk"),
                    ("confidentieel", "Confidentieel"),
                    ("geheim", "Geheim"),
                    ("zeer_geheim", "Zeer geheim"),
                ],
                help_text="Aanduiding van de mate waarin zaakdossiers van ZAAKen van dit ZAAKTYPE voor de openbaarheid bestemd zijn. Indien de zaak bij het aanmaken geen vertrouwelijkheidaanduiding krijgt, dan wordt deze waarde gezet.",
                max_length=20,
                verbose_name="vertrouwelijkheidaanduiding",
            ),
        ),
        migrations.AlterField(
            model_name="zaaktypenrelatie",
            name="aard_relatie",
            field=models.CharField(
                choices=[
                    ("vervolg", "Vervolg"),
                    ("bijdrage", "Bijdrage"),
                    ("onderwerp", "Onderwerp"),
                ],
                help_text="Omschrijving van de aard van de relatie van zaken van het ZAAKTYPE tot zaken van het andere ZAAKTYPE",
                max_length=15,
                verbose_name="aard relatie",
            ),
        ),
        migrations.RemoveField(model_name="checklistitem", name="verplicht"),
        migrations.RemoveField(model_name="statustype", name="informeren"),
        migrations.RemoveField(model_name="zaakobjecttype", name="ander_objecttype"),
        migrations.AddField(
            model_name="checklistitem",
            name="verplicht",
            field=models.BooleanField(
                default=False,
                help_text="Het al dan niet verplicht zijn van controle van het aandachtspunt voorafgaand aan het bereiken van de status van het gerelateerde STATUSTYPE.",
                verbose_name="verplicht",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="statustype",
            name="informeren",
            field=models.BooleanField(
                default=False,
                help_text="Aanduiding die aangeeft of na het zetten van een STATUS van dit STATUSTYPE de Initiator moet worden geïnformeerd over de statusovergang.",
                verbose_name="informeren",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zaakobjecttype",
            name="ander_objecttype",
            field=models.BooleanField(
                default=False,
                help_text="Aanduiding waarmee wordt aangegeven of het ZAAKOBJECTTYPE een ander, niet in RSGB en RGBZ voorkomend, objecttype betreft",
                verbose_name="ander objecttype",
            ),
            preserve_default=False,
        ),
    ]
