# Generated by Django 2.2.3 on 2019-07-12 16:34

from django.db import migrations
from django.db.models import F, Value
from django.db.models.functions import Lower, Replace

from vng_api_common.db.operations import (
    RolomschrijvingUpdate,
    RoltypesUpdate,
    ZaakobjecttypesUpdate,
)


def forward(apps, schema_editor):
    EigenschapSpecificatie = apps.get_model("datamodel", "EigenschapSpecificatie")
    EigenschapSpecificatie.objects.all().update(
        formaat=Lower(Replace(F("formaat"), Value(" "), Value("_")))
    )

    InformatieObjectType = apps.get_model("datamodel", "InformatieObjectType")
    InformatieObjectType.objects.all().update(
        vertrouwelijkheidaanduiding=Lower(
            Replace(F("vertrouwelijkheidaanduiding"), Value(" "), Value("_"))
        )
    )

    MogelijkeBetrokkene = apps.get_model("datamodel", "MogelijkeBetrokkene")
    MogelijkeBetrokkene.objects.all().update(
        betrokkene_type=Lower(
            Replace(
                Replace(F("betrokkene_type"), Value(" "), Value("_")),
                Value("-"),
                Value("_"),
            )
        )
    )

    ZaakType = apps.get_model("datamodel", "ZaakType")
    ZaakType.objects.all().update(
        vertrouwelijkheidaanduiding=Lower(
            Replace(F("vertrouwelijkheidaanduiding"), Value(" "), Value("_"))
        ),
        indicatie_intern_of_extern=Lower(
            Replace(F("indicatie_intern_of_extern"), Value(" "), Value("_"))
        ),
    )

    ZaakInformatieObjectType = apps.get_model("datamodel", "ZaakInformatieObjectType")
    ZaakInformatieObjectType.objects.all().update(
        richting=Lower(Replace(F("richting"), Value(" "), Value("_")))
    )

    ZaakInformatieObjectTypeArchiefregime = apps.get_model(
        "datamodel", "ZaakInformatieObjectTypeArchiefregime"
    )
    ZaakInformatieObjectTypeArchiefregime.objects.all().update(
        archiefnominatie=Lower(Replace(F("archiefnominatie"), Value(" "), Value("_")))
    )

    ZaakTypenRelatie = apps.get_model("datamodel", "ZaakTypenRelatie")
    ZaakTypenRelatie.objects.all().update(
        aard_relatie=Lower(Replace(F("aard_relatie"), Value(" "), Value("_")))
    )


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0103_auto_20190712_1833")]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop),
        RolomschrijvingUpdate("datamodel.RolType", "omschrijving_generiek"),
        RoltypesUpdate("datamodel.MogelijkeBetrokkene", "betrokkene_type"),
        ZaakobjecttypesUpdate(
            "datamodel.ResultaatType", "brondatum_archiefprocedure_objecttype"
        ),
    ]
