# Generated by Django 2.2.3 on 2019-07-12 16:34

from django.db import migrations
from django.db.models import F, Value
from django.db.models.functions import Lower, Replace


def forward(apps, schema_editor):
    EigenschapSpecificatie = apps.get_model("datamodel", "EigenschapSpecificatie")
    EigenschapSpecificatie.objects.all().update(
        formaat=Lower(Replace(F('formaat'), Value(' '), Value('_'))),
    )

    InformatieObjectType = apps.get_model("datamodel", "InformatieObjectType")
    InformatieObjectType.objects.all().update(
        vertrouwelijkheidaanduiding=Lower(Replace(F('vertrouwelijkheidaanduiding'), Value(' '), Value('_'))),
    )

    MogelijkeBetrokkene = apps.get_model("datamodel", "MogelijkeBetrokkene")
    MogelijkeBetrokkene.objects.all().update(
        betrokkene_type=Lower(Replace(Replace(F('betrokkene_type'), Value(' '), Value('_')), Value('-'), Value('_'))),
    )

    ResultaatType = apps.get_model("datamodel", "ResultaatType")
    ResultaatType.objects.all().update(
        brondatum_archiefprocedure_objecttype=Lower(Replace(F('brondatum_archiefprocedure_objecttype'), Value(' '), Value('_'))),
    )

    RolType = apps.get_model("datamodel", "RolType")
    RolType.objects.all().update(
        omschrijving_generiek=Lower(Replace(Replace(Replace(F('omschrijving_generiek'), Value(' '), Value('_')), Value('-'), Value('_')), Value('ö'), Value('o'))),
    )

    ZaakType = apps.get_model("datamodel", "ZaakType")
    ZaakType.objects.all().update(
        vertrouwelijkheidaanduiding=Lower(Replace(F('vertrouwelijkheidaanduiding'), Value(' '), Value('_'))),
        indicatie_intern_of_extern=Lower(Replace(F('indicatie_intern_of_extern'), Value(' '), Value('_'))),
    )

    ZaakInformatieObjectType = apps.get_model("datamodel", "ZaakInformatieObjectType")
    ZaakInformatieObjectType.objects.all().update(
        richting=Lower(Replace(F('richting'), Value(' '), Value('_'))),
    )

    ZaakInformatieObjectTypeArchiefregime = apps.get_model("datamodel", "ZaakInformatieObjectTypeArchiefregime")
    ZaakInformatieObjectTypeArchiefregime.objects.all().update(
        archiefnominatie=Lower(Replace(F('archiefnominatie'), Value(' '), Value('_'))),
    )

    ZaakTypenRelatie = apps.get_model("datamodel", "ZaakTypenRelatie")
    ZaakTypenRelatie.objects.all().update(
        aard_relatie=Lower(Replace(F('aard_relatie'), Value(' '), Value('_'))),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0103_auto_20190712_1833'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
