# Generated by Django 2.2.3 on 2019-07-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0107_auto_20190715_1644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MogelijkeBetrokkene',
        ),
    ]
