# Generated by Django 2.2.3 on 2019-07-29 10:32

from django.db import migrations

from vng_api_common.db.operations import UpdateChoiceValues

from ..choices import FormaatChoices


class FormaatUpdate(UpdateChoiceValues):
    mapping = {
        "datum (jjjjmmdd)": FormaatChoices.datum,
        "datum/tijd (jjjjmmdduummss)": FormaatChoices.datum_tijd,
    }


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0108_delete_mogelijkebetrokkene")]

    operations = [FormaatUpdate("datamodel.EigenschapSpecificatie", "formaat")]
