# Generated by Django 2.2.4 on 2019-09-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0110_auto_20190729_1041")]

    operations = [
        migrations.AlterField(
            model_name="besluittype",
            name="informatieobjecttypes",
            field=models.ManyToManyField(
                blank=True,
                help_text="URL-referenties naar het INFORMATIEOBJECTTYPE van informatieobjecten waarin besluiten van dit BESLUITTYPE worden vastgelegd.",
                related_name="besluittypen",
                to="datamodel.InformatieObjectType",
                verbose_name="informatieobjecttype",
            ),
        ),
        migrations.AlterField(
            model_name="besluittype",
            name="zaaktypes",
            field=models.ManyToManyField(
                help_text="ZAAKTYPE met ZAAKen die relevant kunnen zijn voor dit BESLUITTYPE",
                related_name="besluittypen",
                to="datamodel.ZaakType",
                verbose_name="zaaktypes",
            ),
        ),
        migrations.AlterField(
            model_name="informatieobjecttype",
            name="zaaktypes",
            field=models.ManyToManyField(
                help_text="ZAAKTYPE met ZAAKen die relevant kunnen zijn voor dit INFORMATIEOBJECTTYPE",
                related_name="informatieobjecttypes",
                through="datamodel.ZaakInformatieobjectType",
                to="datamodel.ZaakType",
                verbose_name="zaaktypes",
            ),
        ),
    ]
