# Generated by Django 2.2.4 on 2019-10-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0112_auto_20191022_1333"),
        ("datamodel", "0111_auto_20191009_0838"),
    ]

    operations = []
