# Generated by Django 2.2.4 on 2019-10-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0114_migrate_deelzaaktypen_content")]

    operations = [
        migrations.RemoveField(model_name="zaaktype", name="is_deelzaaktype_van")
    ]
