# Generated by Django 2.2.4 on 2019-11-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0115_remove_zaaktype_is_deelzaaktype_van"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="zaakobjecttype", unique_together=None,),
        migrations.RemoveField(model_name="zaakobjecttype", name="is_relevant_voor",),
        migrations.RemoveField(model_name="zaakobjecttype", name="statustype",),
        migrations.RemoveField(
            model_name="resultaattype", name="heeft_verplichte_zot",
        ),
        migrations.RemoveField(model_name="zaaktype", name="broncatalogus",),
        migrations.RemoveField(model_name="zaaktype", name="bronzaaktype",),
        migrations.RemoveField(model_name="zaaktype", name="formulier",),
        migrations.DeleteModel(name="BronCatalogus",),
        migrations.DeleteModel(name="BronZaakType",),
        migrations.DeleteModel(name="Formulier",),
        migrations.DeleteModel(name="ZaakObjectType",),
    ]
