# Generated by Django 2.2.4 on 2019-11-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0118_auto_20191112_1119"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roltype",
            name="omschrijving",
            field=models.CharField(
                help_text="Omschrijving van de aard van de ROL.",
                max_length=100,
                verbose_name="omschrijving",
            ),
        ),
    ]
