# Generated by Django 2.2.4 on 2019-11-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0118_auto_20191112_1119"),
        ("datamodel", "0113_merge_20191023_0938"),
    ]

    operations = []
