# Generated by Django 2.2.4 on 2019-11-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0119_auto_20191114_1035"),
    ]

    operations = [
        migrations.RenameField(
            model_name="besluittype",
            old_name="resultaattypes",
            new_name="resultaattypen",
        ),
        migrations.RenameField(
            model_name="besluittype", old_name="zaaktypes", new_name="zaaktypen",
        ),
        migrations.AlterField(
            model_name="besluittype",
            name="informatieobjecttypen",
            field=models.ManyToManyField(
                blank=True,
                help_text="URL-referenties naar het INFORMATIEOBJECTTYPE van informatieobjecten waarin besluiten van dit BESLUITTYPE worden vastgelegd.",
                related_name="besluittypen",
                to="datamodel.InformatieObjectType",
                verbose_name="informatieobjecttypen",
            ),
        ),
    ]
