# Generated by Django 2.2.4 on 2019-11-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0120_auto_20191114_1100"),
    ]

    operations = [
        migrations.RenameField(
            model_name="informatieobjecttype",
            old_name="zaaktypes",
            new_name="zaaktypen",
        ),
        migrations.AlterField(
            model_name="besluittype",
            name="zaaktypen",
            field=models.ManyToManyField(
                help_text="ZAAKTYPE met ZAAKen die relevant kunnen zijn voor dit BESLUITTYPE",
                related_name="besluittypen",
                to="datamodel.ZaakType",
                verbose_name="zaaktypen",
            ),
        ),
    ]
