# Generated by Django 2.2.4 on 2019-11-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0121_auto_20191114_1136"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informatieobjecttype",
            name="zaaktypen",
            field=models.ManyToManyField(
                help_text="ZAAKTYPE met ZAAKen die relevant kunnen zijn voor dit INFORMATIEOBJECTTYPE",
                related_name="informatieobjecttypen",
                through="datamodel.ZaakInformatieobjectType",
                to="datamodel.ZaakType",
                verbose_name="zaaktypen",
            ),
        ),
    ]
