# Generated by Django 2.2.4 on 2019-11-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0122_auto_20191114_1136"),
        ("datamodel", "0119_merge_20191114_1020"),
    ]

    operations = []
