# Generated by Django 2.2.4 on 2020-10-12 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0122_auto_20191114_1136"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eigenschap",
            name="specificatie_van_eigenschap",
            field=models.ForeignKey(
                help_text="Attribuutkenmerken van de eigenschap",
                on_delete=django.db.models.deletion.CASCADE,
                to="datamodel.EigenschapSpecificatie",
                verbose_name="specificatie van eigenschap",
            ),
        ),
        migrations.AlterField(
            model_name="resultaattype",
            name="brondatum_archiefprocedure_afleidingswijze",
            field=models.CharField(
                choices=[
                    ("afgehandeld", "Afgehandeld"),
                    ("ander_datumkenmerk", "Ander datumkenmerk"),
                    ("eigenschap", "Eigenschap"),
                    ("gerelateerde_zaak", "Gerelateerde zaak"),
                    ("hoofdzaak", "Hoofdzaak"),
                    ("ingangsdatum_besluit", "Ingangsdatum besluit"),
                    ("termijn", "Termijn"),
                    ("vervaldatum_besluit", "Vervaldatum besluit"),
                    ("zaakobject", "Zaakobject"),
                ],
                help_text="Wijze van bepalen van de brondatum.",
                max_length=20,
                verbose_name="afleidingswijze brondatum",
            ),
        ),
    ]
