# Generated by Django 2.2.4 on 2020-10-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0123_merge_20191114_1149"),
        ("datamodel", "0125_auto_20201023_1545"),
    ]

    operations = []
