# Generated by Django 2.2.4 on 2021-12-02 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0126_merge_20201027_1221"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogus",
            name="datum_begin_versie",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Datum waarop de versie van de zaaktypecatalogus van toepassing is geworden.",
                verbose_name="begindatum versie",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="catalogus",
            name="naam",
            field=models.CharField(
                default="",
                help_text="De benaming die is gegeven aan de zaaktypecatalogus.",
                max_length=200,
                verbose_name="naam",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="catalogus",
            name="versie",
            field=models.CharField(
                default="",
                help_text="Versie-aanduiding van de van toepassing zijnde zaaktypecatalogus.",
                max_length=20,
                verbose_name="versie",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="catalogus",
            name="contactpersoon_beheer_naam",
            field=models.CharField(
                help_text="De naam van de contactpersoon die verantwoordelijk is voor het beheer van de CATALOGUS.",
                max_length=40,
                verbose_name="naam contactpersoon",
            ),
        ),
    ]
