# Generated by Django 2.2.28 on 2022-04-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0126_merge_20201027_1221"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="informatieobjecttypeomschrijvinggeneriek",
            name="_etag",
        ),
    ]
