# Generated by Django 2.2.4 on 2021-11-19 13:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0126_merge_20201027_1221"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZaakObjectType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_etag",
                    models.CharField(
                        editable=False,
                        help_text="MD5 hash of the resource representation in its current version.",
                        max_length=32,
                        verbose_name="etag value",
                    ),
                ),
                (
                    "datum_begin_geldigheid",
                    models.DateField(
                        help_text="De datum waarop het is ontstaan.",
                        verbose_name="datum begin geldigheid",
                    ),
                ),
                (
                    "datum_einde_geldigheid",
                    models.DateField(
                        blank=True,
                        help_text="De datum waarop het is opgeheven.",
                        null=True,
                        verbose_name="datum einde geldigheid",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "ander_objecttype",
                    models.BooleanField(
                        help_text="Aanduiding waarmee wordt aangegeven of het ZAAKOBJECTTYPE een ander, niet in RSGB en RGBZ voorkomend, objecttype betreft.",
                        verbose_name="Ander objecttype",
                    ),
                ),
                (
                    "objecttype",
                    models.URLField(
                        help_text="URL-referentie naar de OBJECTTYPE waartoe dit ZAAKOBJECTTYPE behoort.",
                        verbose_name="Objecttype",
                    ),
                ),
                (
                    "relatie_omschrijving",
                    models.CharField(
                        help_text="Omschrijving van de betrekking van het Objecttype op zaken van het gerelateerde ZAAKTYPE.",
                        max_length=80,
                        verbose_name="Relatie omschrijving",
                    ),
                ),
                (
                    "catalogus",
                    models.ForeignKey(
                        help_text="URL-referentie naar de CATALOGUS waartoe dit ZAAKOBJECTTYPE behoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datamodel.Catalogus",
                        verbose_name="Catalogus",
                    ),
                ),
                (
                    "zaaktype",
                    models.ForeignKey(
                        help_text="URL-referentie naar de ZAAKTYPE waartoe dit ZAAKOBJECTTYPE behoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objecttypen",
                        to="datamodel.ZaakType",
                        verbose_name="Zaaktype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zaakobjecttype",
                "verbose_name_plural": "Zaakobjecttypen",
                "ordering": ("catalogus", "datum_begin_geldigheid"),
            },
        ),
        migrations.AddField(
            model_name="resultaattype",
            name="zaakobjecttypen",
            field=models.ManyToManyField(
                help_text="De ZAAKOBJECTTYPEn die verplicht gerelateerd moeten zijn aan ZAAKen van dit ZAAKTYPE voordat een resultaat van dit RESULTAATTYPE kan worden gezet.",
                related_name="resultaattypen",
                to="datamodel.ZaakObjectType",
                verbose_name="Zaakobjecttypen",
            ),
        ),
        migrations.AddField(
            model_name="statustype",
            name="zaakobjecttype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statustypen",
                to="datamodel.ZaakObjectType",
                verbose_name="Zaakobjecttypen",
            ),
        ),
    ]
