# Generated by Django 2.2.4 on 2021-12-02 09:44

from django.db import migrations


def add_defaults(apps, schema_editor):
    Catalogus = apps.get_model("datamodel", "Catalogus")

    for catalogus in Catalogus.objects.all():
        catalogus.name = f"Catalogus {catalogus.rsin}"
        catalogus.version = "1"
        catalogus.save()


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0127_auto_20211202_0934"),
    ]

    operations = [migrations.RunPython(add_defaults)]
