# Generated by Django 2.2.4 on 2021-12-21 13:15

from django.db import migrations, models

import vng_api_common.fields
import vng_api_common.validators

import ztc.datamodel.validators


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0128_auto_20211221_0922"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaaktype",
            name="broncatalogus_domein",
            field=models.CharField(
                blank=True,
                help_text="Het domein van de CATALOGUS waaraan het ZAAKTYPE is ontleend.",
                max_length=5,
                null=True,
                validators=[ztc.datamodel.validators.validate_uppercase],
                verbose_name="broncatalogus domein",
            ),
        ),
        migrations.AddField(
            model_name="zaaktype",
            name="broncatalogus_rsin",
            field=vng_api_common.fields.RSINField(
                blank=True,
                help_text="Het RSIN van de INGESCHREVEN NIET-NATUURLIJK PERSOON die beheerder is van de CATALOGUS waaraan het ZAAKTYPE is ontleend.",
                max_length=9,
                null=True,
                verbose_name="broncatalogus rsin",
            ),
        ),
        migrations.AddField(
            model_name="zaaktype",
            name="broncatalogus_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="URL-referentie broncatalogus"
            ),
        ),
        migrations.AddField(
            model_name="zaaktype",
            name="bronzaaktype_identificatie",
            field=models.CharField(
                blank=True,
                help_text="De Zaaktype-identificatie van het bronzaaktype binnen de CATALOGUS.",
                max_length=50,
                null=True,
                validators=[vng_api_common.validators.AlphanumericExcludingDiacritic()],
                verbose_name="bronzaaktype identificatie",
            ),
        ),
        migrations.AddField(
            model_name="zaaktype",
            name="bronzaaktype_omschrijving",
            field=models.CharField(
                blank=True,
                help_text="De Zaaktype-omschrijving van het bronzaaktype, zoals gehanteerd in de Broncatalogus.",
                max_length=80,
                null=True,
                verbose_name="bronzaaktype omschrijving",
            ),
        ),
        migrations.AddField(
            model_name="zaaktype",
            name="bronzaaktype_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="URL-referentie bronzaaktype"
            ),
        ),
    ]
