# Generated by Django 2.2.4 on 2021-12-02 10:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0128_auto_20211202_0944"),
    ]

    operations = [
        migrations.AddField(
            model_name="eigenschap",
            name="datum_begin_geldigheid",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="De datum waarop het is ontstaan.",
                verbose_name="datum begin geldigheid",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eigenschap",
            name="datum_einde_geldigheid",
            field=models.DateField(
                blank=True,
                help_text="De datum waarop het is opgeheven.",
                null=True,
                verbose_name="datum einde geldigheid",
            ),
        ),
    ]
