# Generated by Django 2.2.4 on 2021-12-14 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0129_auto_20211202_1048"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultaattype",
            name="catalogus",
            field=models.ForeignKey(
                blank=True,
                help_text="URL-referentie naar de CATALOGUS waartoe dit RESULTAATTYPE behoort.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="datamodel.Catalogus",
                verbose_name="catalogus",
            ),
        ),
        migrations.AddField(
            model_name="resultaattype",
            name="datum_begin_geldigheid",
            field=models.DateField(
                blank=True,
                help_text="De datum waarop het is ontstaan.",
                null=True,
                verbose_name="datum begin geldigheid",
            ),
        ),
        migrations.AddField(
            model_name="resultaattype",
            name="datum_einde_geldigheid",
            field=models.DateField(
                blank=True,
                help_text="De datum waarop het is opgeheven.",
                null=True,
                verbose_name="datum einde geldigheid",
            ),
        ),
        migrations.AddField(
            model_name="resultaattype",
            name="indicatie_specifiek",
            field=models.BooleanField(
                blank=True,
                help_text="Aanduiding of het, vanuit archiveringsoptiek, een resultaattype betreft dat specifiek is voor een bepaalde procesobjectaard.",
                null=True,
                verbose_name="indicatie specifiek",
            ),
        ),
        migrations.AddField(
            model_name="resultaattype",
            name="informatieobjecttypen",
            field=models.ManyToManyField(
                blank=True,
                help_text="De INFORMATIEOBJECTTYPEn die verplicht aanwezig moeten zijn in het zaakdossier van ZAAKen van dit ZAAKTYPE voordat een resultaat van dit RESULTAATTYPE kan worden gezet.",
                to="datamodel.InformatieObjectType",
                verbose_name="informatieobjecttypen",
            ),
        ),
        migrations.AddField(
            model_name="resultaattype",
            name="procesobjectaard",
            field=models.CharField(
                blank=True,
                help_text="Omschrijving van het object, subject of gebeurtenis waarop, vanuit archiveringsoptiek, het resultaattype bij zaken van dit type betrekking heeft.",
                max_length=200,
                null=True,
                verbose_name="procesobjectaard",
            ),
        ),
        migrations.AddField(
            model_name="resultaattype",
            name="procestermijn",
            field=models.DurationField(
                blank=True,
                help_text="De periode dat het zaakdossier na afronding van de zaak actief gebruikt en/of geraadpleegd wordt ter ondersteuning van de taakuitoefening van de organisatie.",
                null=True,
                verbose_name="procestermijn",
            ),
        ),
    ]
