# Generated by Django 2.2.4 on 2021-12-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0129_auto_20211221_1315"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statustype",
            name="doorlooptijd_status",
        ),
    ]
