# Generated by Django 2.2.4 on 2021-12-23 10:27

from django.db import migrations

import vng_api_common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0130_remove_statustype_doorlooptijd_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="statustype",
            name="doorlooptijd_status",
            field=vng_api_common.fields.DaysDurationField(
                blank=True,
                help_text="De door de zaakbehandelende organisatie(s) gestelde norm voor de doorlooptijd voor het bereiken van STATUSsen van dit STATUSTYPE bij het desbetreffende ZAAKTYPE.",
                max_duration=999,
                min_duration=1,
                null=True,
                verbose_name="doorlooptijd status",
            ),
        ),
    ]
