# Generated by Django 2.2.4 on 2021-12-14 14:25

from django.db import migrations

import relativedeltafield


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0130_auto_20211214_1002"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultaattype",
            name="brondatum_archiefprocedure_procestermijn",
            field=relativedeltafield.RelativeDeltaField(
                blank=True,
                help_text="De periode dat het zaakdossier na afronding van de zaak actief gebruikt en/of geraadpleegd wordt ter ondersteuning van de taakuitoefening van de organisatie. Enkel relevant indien de afleidingswijze 'termijn' is.",
                null=True,
                verbose_name="brondatum procestermijn",
            ),
        ),
        migrations.AlterField(
            model_name="resultaattype",
            name="procestermijn",
            field=relativedeltafield.RelativeDeltaField(
                blank=True,
                help_text="De periode dat het zaakdossier na afronding van de zaak actief gebruikt en/of geraadpleegd wordt ter ondersteuning van de taakuitoefening van de organisatie.",
                null=True,
                verbose_name="procestermijn",
            ),
        ),
    ]
