# Generated by Django 2.2.4 on 2021-12-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0131_auto_20211214_1425"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogus",
            name="datum_begin_versie",
            field=models.DateField(
                blank=True,
                help_text="Datum waarop de versie van de zaaktypecatalogus van toepassing is geworden.",
                null=True,
                verbose_name="begindatum versie",
            ),
        ),
        migrations.AlterField(
            model_name="catalogus",
            name="naam",
            field=models.CharField(
                blank=True,
                help_text="De benaming die is gegeven aan de zaaktypecatalogus.",
                max_length=200,
                null=True,
                verbose_name="naam",
            ),
        ),
        migrations.AlterField(
            model_name="catalogus",
            name="versie",
            field=models.CharField(
                blank=True,
                help_text="Versie-aanduiding van de van toepassing zijnde zaaktypecatalogus.",
                max_length=20,
                null=True,
                verbose_name="versie",
            ),
        ),
    ]
