# Generated by Django 2.2.28 on 2022-06-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0127_remove_informatieobjecttypeomschrijvinggeneriek__etag"),
        ("datamodel", "0131_statustype_doorlooptijd_status"),
    ]

    operations = []
