# Generated by Django 2.2.4 on 2022-05-04 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0131_statustype_doorlooptijd_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statustype",
            name="doorlooptijd_status",
        ),
        migrations.AddField(
            model_name="statustype",
            name="doorlooptijd_periode",
            field=models.IntegerField(
                help_text="De door de zaakbehandelende organisatie(s) gestelde norm voor de doorlooptijd voor het bereiken van STATUSsen van dit STATUSTYPE bij het desbetreffende ZAAKTYPE.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="doorlooptijd periode",
            ),
        ),
        migrations.AddField(
            model_name="statustype",
            name="periode_eenheid",
            field=models.CharField(
                choices=[
                    ("werkdagen", "Werkdagen"),
                    ("kalenderdagen", "Kalenderdagen"),
                    ("weken", "Weken"),
                    ("maanden", "Maanden"),
                    ("jaren", "Jaren"),
                ],
                default="werkdagen",
                help_text="De tijdseenheid waarin een doorlooptijd periode wordt uitgedrukt",
                max_length=20,
                null=True,
                verbose_name="doorlooptijd periode eenheid",
            ),
        ),
    ]
