# Generated by Django 2.2.4 on 2021-12-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0132_auto_20211215_0953"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eigenschap",
            name="datum_begin_geldigheid",
            field=models.DateField(
                blank=True,
                help_text="De datum waarop het is ontstaan.",
                null=True,
                verbose_name="datum begin geldigheid",
            ),
        ),
    ]
