# Generated by Django 2.2.4 on 2022-07-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0132_merge_20220621_1542"),
        ("datamodel", "0132_auto_20220517_0842"),
    ]

    operations = []
