# Generated by Django 2.2.4 on 2022-07-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0132_merge_20220621_1542"),
    ]

    operations = [
        migrations.AddField(
            model_name="besluittype",
            name="datum_begin_object",
            field=models.DateField(
                blank=True,
                help_text="De datum waarop de eerst versie van het object ontstaan is.",
                null=True,
                verbose_name="datum begin object",
            ),
        ),
        migrations.AddField(
            model_name="besluittype",
            name="datum_einde_object",
            field=models.DateField(
                blank=True,
                help_text="De datum van de aller laatste versie van het object.",
                null=True,
                verbose_name="datum einde object",
            ),
        ),
        migrations.AddField(
            model_name="eigenschap",
            name="datum_begin_object",
            field=models.DateField(
                blank=True,
                help_text="De datum waarop de eerst versie van het object ontstaan is.",
                null=True,
                verbose_name="datum begin object",
            ),
        ),
        migrations.AddField(
            model_name="eigenschap",
            name="datum_einde_object",
            field=models.DateField(
                blank=True,
                help_text="De datum van de aller laatste versie van het object.",
                null=True,
                verbose_name="datum einde object",
            ),
        ),
        migrations.AddField(
            model_name="informatieobjecttype",
            name="datum_begin_object",
            field=models.DateField(
                blank=True,
                help_text="De datum waarop de eerst versie van het object ontstaan is.",
                null=True,
                verbose_name="datum begin object",
            ),
        ),
        migrations.AddField(
            model_name="informatieobjecttype",
            name="datum_einde_object",
            field=models.DateField(
                blank=True,
                help_text="De datum van de aller laatste versie van het object.",
                null=True,
                verbose_name="datum einde object",
            ),
        ),
        migrations.AddField(
            model_name="informatieobjecttypeomschrijvinggeneriek",
            name="datum_begin_object",
            field=models.DateField(
                blank=True,
                help_text="De datum waarop de eerst versie van het object ontstaan is.",
                null=True,
                verbose_name="datum begin object",
            ),
        ),
        migrations.AddField(
            model_name="informatieobjecttypeomschrijvinggeneriek",
            name="datum_einde_object",
            field=models.DateField(
                blank=True,
                help_text="De datum van de aller laatste versie van het object.",
                null=True,
                verbose_name="datum einde object",
            ),
        ),
        migrations.AddField(
            model_name="resultaattype",
            name="datum_begin_object",
            field=models.DateField(
                blank=True,
                help_text="De datum waarop de eerst versie van het object ontstaan is.",
                null=True,
                verbose_name="datum begin object",
            ),
        ),
        migrations.AddField(
            model_name="resultaattype",
            name="datum_einde_object",
            field=models.DateField(
                blank=True,
                help_text="De datum van de aller laatste versie van het object.",
                null=True,
                verbose_name="datum einde object",
            ),
        ),
        migrations.AddField(
            model_name="roltype",
            name="datum_begin_object",
            field=models.DateField(
                blank=True,
                help_text="De datum waarop de eerst versie van het object ontstaan is.",
                null=True,
                verbose_name="datum begin object",
            ),
        ),
        migrations.AddField(
            model_name="roltype",
            name="datum_einde_object",
            field=models.DateField(
                blank=True,
                help_text="De datum van de aller laatste versie van het object.",
                null=True,
                verbose_name="datum einde object",
            ),
        ),
        migrations.AddField(
            model_name="statustype",
            name="datum_begin_object",
            field=models.DateField(
                blank=True,
                help_text="De datum waarop de eerst versie van het object ontstaan is.",
                null=True,
                verbose_name="datum begin object",
            ),
        ),
        migrations.AddField(
            model_name="statustype",
            name="datum_einde_object",
            field=models.DateField(
                blank=True,
                help_text="De datum van de aller laatste versie van het object.",
                null=True,
                verbose_name="datum einde object",
            ),
        ),
        migrations.AddField(
            model_name="zaakobjecttype",
            name="datum_begin_object",
            field=models.DateField(
                blank=True,
                help_text="De datum waarop de eerst versie van het object ontstaan is.",
                null=True,
                verbose_name="datum begin object",
            ),
        ),
        migrations.AddField(
            model_name="zaakobjecttype",
            name="datum_einde_object",
            field=models.DateField(
                blank=True,
                help_text="De datum van de aller laatste versie van het object.",
                null=True,
                verbose_name="datum einde object",
            ),
        ),
        migrations.AddField(
            model_name="zaaktype",
            name="datum_begin_object",
            field=models.DateField(
                blank=True,
                help_text="De datum waarop de eerst versie van het object ontstaan is.",
                null=True,
                verbose_name="datum begin object",
            ),
        ),
        migrations.AddField(
            model_name="zaaktype",
            name="datum_einde_object",
            field=models.DateField(
                blank=True,
                help_text="De datum van de aller laatste versie van het object.",
                null=True,
                verbose_name="datum einde object",
            ),
        ),
    ]
