# Generated by Django 2.2.4 on 2022-07-11 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0133_auto_20220706_1030"),
    ]

    operations = [
        migrations.AddField(
            model_name="eigenschap",
            name="catalogus",
            field=models.ForeignKey(
                blank=True,
                help_text="URL-referentie naar de CATALOGUS waartoe dit EIGENSCHAP behoort.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="datamodel.Catalogus",
                verbose_name="catalogus",
            ),
        ),
        migrations.AddField(
            model_name="statustype",
            name="catalogus",
            field=models.ForeignKey(
                blank=True,
                help_text="URL-referentie naar de CATALOGUS waartoe dit STATUSTYPE behoort.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="datamodel.Catalogus",
                verbose_name="catalogus",
            ),
        ),
        migrations.AddField(
            model_name="zaakinformatieobjecttype",
            name="catalogus",
            field=models.ForeignKey(
                blank=True,
                help_text="URL-referentie naar de CATALOGUS waartoe dit ZAAKINFORMATIEOBJECTTYPE behoort.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="datamodel.Catalogus",
                verbose_name="catalogus",
            ),
        ),
    ]
