# Generated by Django 2.2.4 on 2022-07-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0133_auto_20220706_1030"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultaattype",
            name="omschrijving",
            field=models.CharField(
                help_text="Omschrijving van de aard van resultaten van het RESULTAATTYPE.",
                max_length=30,
                verbose_name="omschrijving",
            ),
        ),
    ]
