# Generated by Django 3.2.14 on 2022-07-14 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0134_auto_20220707_1447"),
        ("datamodel", "0134_auto_20220711_0841"),
    ]

    operations = []
