# Generated by Django 3.2.14 on 2022-11-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0135_merge_0134_auto_20220707_1447_0134_auto_20220711_0841"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="besluittype",
            unique_together=set(),
        ),
    ]
