# Generated by Django 3.2.14 on 2022-12-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0135_merge_0134_auto_20220707_1447_0134_auto_20220711_0841"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="zaakinformatieobjecttype",
            options={
                "verbose_name": "Zaak-Informatieobject-Type",
                "verbose_name_plural": "Zaak-Informatieobject-Typen",
            },
        ),
        migrations.AlterUniqueTogether(
            name="zaakinformatieobjecttype",
            unique_together=set(),
        ),
    ]
