# Generated by Django 2.2.4 on 2021-12-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0135_auto_20211215_1346"),
    ]

    operations = [
        migrations.AddField(
            model_name="statustype",
            name="datum_begin_geldigheid",
            field=models.DateField(
                blank=True,
                help_text="De datum waarop het is ontstaan.",
                null=True,
                verbose_name="datum begin geldigheid",
            ),
        ),
        migrations.AddField(
            model_name="statustype",
            name="datum_einde_geldigheid",
            field=models.DateField(
                blank=True,
                help_text="De datum waarop het is opgeheven.",
                null=True,
                verbose_name="datum einde geldigheid",
            ),
        ),
        migrations.AddField(
            model_name="statustype",
            name="eigenschappen",
            field=models.ManyToManyField(
                blank=True,
                help_text="de EIGENSCHAPpen die verplicht een waarde moeten hebben gekregen, voordat een STATUS van dit STATUSTYPE kan worden gezet.",
                related_name="statustypen",
                to="datamodel.Eigenschap",
                verbose_name="eigenschappen",
            ),
        ),
    ]
