# Generated by Django 3.2.14 on 2023-03-09 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0136_auto_20230309_1412"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="zaakinformatieobjecttype",
            options={
                "verbose_name": "Zaak-Informatieobject-Type",
                "verbose_name_plural": "Zaak-Informatieobject-Typen",
            },
        ),
        migrations.AlterUniqueTogether(
            name="zaakinformatieobjecttype",
            unique_together=set(),
        ),
    ]
