# Generated by Django 3.2.14 on 2023-03-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0137_auto_20230309_1415"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="zaaktypenrelatie",
            unique_together=set(),
        ),
    ]
